// This file is generated by Astro DB
declare module 'astro:db' {
	export const Tabla1: import("@astrojs/db/runtime").Table<
		"Tabla1",
		{"correo":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"correo","collection":"Tabla1","primaryKey":false,"optional":false}},"nombre":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"nombre","collection":"Tabla1","primaryKey":false,"optional":false}}}
	>;
}
